#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 25 13:55:47 2018

@author: juliaorenstein
"""

import numpy as np
import matplotlib.pyplot as plt
import glob.glob

datafiles = glob.glob('../Data/*.txt')
print datafiles
